### PR TITLE
Resolve issue with wont parse Uint8Array

### PR DESCRIPTION
**Pull request by jiafengwu0301**

### CODE REVIEW

**Review by panva — CHANGES_REQUESTED** [review]
please add a test case for what you’re fixing

**Review by panva — CHANGES_REQUESTED** [review]
I don't understand when this change actually kicks in. Can you elaborate? Using the exposed API, when is `payload` actually passed in as `Uint8Array`?

**Comment by jiafengwu0301** [comment]
When I run my Jest test, it passes a Uint8Array

**Comment by panva** [comment]
> When I run my Jest test, it passes a Uint8Array

What environment?

**Comment by panva** [comment]
It would be helpful if you provided a failing test that uses the public API.

**Comment by jiafengwu0301** [comment]
node 14, jest 24.9.0

**Comment by panva** [comment]
I'm not going to accept this PR without seeing a failing test in the project's test suite, one that uses the public API from the [documentation](https://github.com/panva/paseto/blob/v1.0.7/docs/README.md).

What I get from this conversation so far is that you're probably transpiling this module in which case I will not accommodate such use.

**Pull request closed without merging**
